-- MySQL Script generated by MySQL Workbench
-- Fri Nov 20 15:28:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Local` (
  `Código` INT NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuário` (
  `Email` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Local_Código` INT NOT NULL,
  PRIMARY KEY (`Email`),
  INDEX `fk_Usuário_Local1_idx` (`Local_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Usuário_Local1`
    FOREIGN KEY (`Local_Código`)
    REFERENCES `mydb`.`Local` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lotação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lotação` (
  `ID` INT NOT NULL,
  `Tempo Estimado` TIME NOT NULL,
  `Tamanho/nível` VARCHAR(45) NOT NULL,
  `Estabelecimento_Código` INT NOT NULL,
  PRIMARY KEY (`ID`, `Estabelecimento_Código`),
  INDEX `fk_Lotação_Estabelecimento1_idx` (`Estabelecimento_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Lotação_Estabelecimento1`
    FOREIGN KEY (`Estabelecimento_Código`)
    REFERENCES `mydb`.`Estabelecimento` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pico` (
  `Data` DATETIME NOT NULL,
  `Dia da Semana` INT NOT NULL,
  `Lotação_ID` INT NOT NULL,
  PRIMARY KEY (`Data`),
  INDEX `fk_Pico_Lotação1_idx` (`Lotação_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pico_Lotação1`
    FOREIGN KEY (`Lotação_ID`)
    REFERENCES `mydb`.`Lotação` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estabelecimento` (
  `Código` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(100) NOT NULL,
  `Tempo_Medio_Atendimento` TIME NOT NULL,
  `Local_Código` INT NOT NULL,
  PRIMARY KEY (`Código`),
  INDEX `fk_Estabelecimento_Local1_idx` (`Local_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Estabelecimento_Local1`
    FOREIGN KEY (`Local_Código`)
    REFERENCES `mydb`.`Local` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliação` (
  `Horário` TIME NOT NULL,
  `Comentário` VARCHAR(45) NOT NULL,
  `Nota` INT NOT NULL,
  `Usuário_Email` VARCHAR(45) NOT NULL,
  `Estabelecimento_Código` INT NOT NULL,
  PRIMARY KEY (`Horário`, `Usuário_Email`, `Estabelecimento_Código`),
  INDEX `fk_Avaliação_Usuário_idx` (`Usuário_Email` ASC) VISIBLE,
  INDEX `fk_Avaliação_Estabelecimento1_idx` (`Estabelecimento_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliação_Usuário`
    FOREIGN KEY (`Usuário_Email`)
    REFERENCES `mydb`.`Usuário` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliação_Estabelecimento1`
    FOREIGN KEY (`Estabelecimento_Código`)
    REFERENCES `mydb`.`Estabelecimento` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transporte` (
  `Código` INT NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Risco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rotas` (
  `Código` INT NOT NULL,
  `Distância` INT NOT NULL,
  `Usuário_Email` VARCHAR(45) NOT NULL,
  `Estabelecimento_Código` INT NOT NULL,
  `Transporte_Código` INT NOT NULL,
  PRIMARY KEY (`Código`),
  INDEX `fk_Rotas_Usuário1_idx` (`Usuário_Email` ASC) VISIBLE,
  INDEX `fk_Rotas_Estabelecimento1_idx` (`Estabelecimento_Código` ASC) VISIBLE,
  INDEX `fk_Rotas_Transporte1_idx` (`Transporte_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Rotas_Usuário1`
    FOREIGN KEY (`Usuário_Email`)
    REFERENCES `mydb`.`Usuário` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rotas_Estabelecimento1`
    FOREIGN KEY (`Estabelecimento_Código`)
    REFERENCES `mydb`.`Estabelecimento` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rotas_Transporte1`
    FOREIGN KEY (`Transporte_Código`)
    REFERENCES `mydb`.`Transporte` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `Código` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `Nome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(110) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Frequenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Frequenta` (
  `Usuário_Email` VARCHAR(45) NOT NULL,
  `Estabelecimento_Código` INT NOT NULL,
  PRIMARY KEY (`Usuário_Email`, `Estabelecimento_Código`),
  INDEX `fk_Usuário_has_Estabelecimento_Estabelecimento1_idx` (`Estabelecimento_Código` ASC) VISIBLE,
  INDEX `fk_Usuário_has_Estabelecimento_Usuário1_idx` (`Usuário_Email` ASC) VISIBLE,
  CONSTRAINT `fk_Usuário_has_Estabelecimento_Usuário1`
    FOREIGN KEY (`Usuário_Email`)
    REFERENCES `mydb`.`Usuário` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_has_Estabelecimento_Estabelecimento1`
    FOREIGN KEY (`Estabelecimento_Código`)
    REFERENCES `mydb`.`Estabelecimento` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contém`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contém` (
  `Produtos_Código` INT NOT NULL,
  `Estabelecimento_Código` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Produtos_Código`, `Estabelecimento_Código`),
  INDEX `fk_Produtos_has_Estabelecimento_Estabelecimento1_idx` (`Estabelecimento_Código` ASC) VISIBLE,
  INDEX `fk_Produtos_has_Estabelecimento_Produtos1_idx` (`Produtos_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_has_Estabelecimento_Produtos1`
    FOREIGN KEY (`Produtos_Código`)
    REFERENCES `mydb`.`Produtos` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Estabelecimento_Estabelecimento1`
    FOREIGN KEY (`Estabelecimento_Código`)
    REFERENCES `mydb`.`Estabelecimento` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pertence a`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pertence a` (
  `Estabelecimento_Código` INT NOT NULL,
  `Categoria_Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Estabelecimento_Código`, `Categoria_Nome`),
  INDEX `fk_Estabelecimento_has_Categoria_Categoria1_idx` (`Categoria_Nome` ASC) VISIBLE,
  INDEX `fk_Estabelecimento_has_Categoria_Estabelecimento1_idx` (`Estabelecimento_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Estabelecimento_has_Categoria_Estabelecimento1`
    FOREIGN KEY (`Estabelecimento_Código`)
    REFERENCES `mydb`.`Estabelecimento` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estabelecimento_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_Nome`)
    REFERENCES `mydb`.`Categoria` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
